### ISSUE TITLE
easyvk

### ISSUE THREAD

**Issue by Siptrixed** [tempage/dorynode#23]
node_modules/easyvk/lib/bundle.js:315
  static async call (methodName, data = {}, methodType = 'get', debuggerIS = null, Agent, settings = {}) {
                   ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by Siptrixed** [comment]
just update node
