### ISSUE TITLE
Unable to start node app

### ISSUE THREAD

**Issue by therckenrath** [tempage/dorynode#5]
WARNING: linker: /data/data/io.tempage.dorynode/files/bin/node: unused DT entry: type 0x6ffffffe arg 0x256f78
WARNING: linker: /data/data/io.tempage.dorynode/files/bin/node: unused DT entry: type 0x6fffffff arg 0x3
module.js:471
    throw err;
    ^

Error: Cannot find module '/storage/emulated/0/lpapi'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

**Comment by therckenrath** [comment]
No change after performing the following:
1) npm cache clean
2) remove node_modules folder
3) npm install

**Comment by therckenrath** [comment]
This app runs fine on Node on my laptop, so why am I getting this error?

**Comment by therckenrath** [comment]
Old version of Node, cannot use async
